---
title: "testOptimiseAlpha"
author: "Manikya Alister"
date: "29/11/2022"
output: 
  html_document:
    theme: simplex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("functions/optimiseAlpha.R")
```

```{r}
borders = makeBorders(0:10)
```

# Small True Rectangle

```{r}
# small rectangle 
smallRect = c(2,2,4,4)
# 1 positive 1 negative, small
obs11small = generateObs(1,1,smallRect)

# grid search
gridSmall11 = alphaGridSearch(borders, obs11small)

# trusting participant
a1Small11 = simulatePar(obs11small, borders, alpha = 1)

# weak sampling assumptions participant 
a0Small11 = simulatePar(obs11small, borders, alpha = 0)

# suspicious participant
aNeg1Small11 = simulatePar(obs11small, borders, alpha = -1)
```

```{r}
par(mfrow = c(1,3))

# estimate alphas
a1Small11Fit = fitAlpha(a1Small11, gridSmall11)
plot(a1Small11Fit[,"alpha"], a1Small11Fit[,"prob"])
lines(a1Small11Fit[,"alpha"], a1Small11Fit[,"prob"])

a0Small11Fit = fitAlpha(a0Small11, gridSmall11)
plot(a0Small11Fit[,"alpha"], a0Small11Fit[,"prob"])
lines(a0Small11Fit[,"alpha"], a0Small11Fit[,"prob"])

aNeg1Small11Fit = fitAlpha(aNeg1Small11, gridSmall11)
plot(aNeg1Small11Fit[,"alpha"], aNeg1Small11Fit[,"prob"])
lines(x = aNeg1Small11Fit[,"alpha"], y = aNeg1Small11Fit[,"prob"])

```
```{r}
# small rectangle 
smallRect = c(2,2,4,4)
# 1 positive 1 negative, small
obs22small = generateObs(2,2,smallRect)

# grid search
gridSmall22 = alphaGridSearch(borders, obs22small)

# trusting participant
a1Small22 = simulatePar(obs22small, borders, alpha = 1)

# weak sampling assumptions participant 
a0Small22 = simulatePar(obs22small, borders, alpha = 0)

# suspicious participant
aNeg1Small22 = simulatePar(obs22small, borders, alpha = -1)
```

```{r}
par(mfrow = c(1,3))

# estimate alphas
a1Small22Fit = fitAlpha(a1Small22, gridSmall22)
plot(a1Small22Fit[,"alpha"], a1Small22Fit[,"prob"])
lines(a1Small22Fit[,"alpha"], a1Small22Fit[,"prob"])

a0Small22Fit = fitAlpha(a0Small22, gridSmall22)
plot(a0Small22Fit[,"alpha"], a0Small22Fit[,"prob"])
lines(a0Small22Fit[,"alpha"], a0Small22Fit[,"prob"])

aNeg1Small22Fit = fitAlpha(aNeg1Small22, gridSmall22)
plot(aNeg1Small22Fit[,"alpha"], aNeg1Small22Fit[,"prob"])
lines(x = aNeg1Small22Fit[,"alpha"], y = aNeg1Small22Fit[,"prob"])

```
# Large True Rectangle

```{r}
# small rectangle 
largeRect = c(2,2,9,9)
# 1 positive 1 negative, Large
obs11Large = generateObs(1,1,largeRect)

# grid search
gridLarge11 = alphaGridSearch(borders, obs11Large)

# trusting participant
a1Large11 = simulatePar(obs11Large, borders, alpha = 1)

# weak sampling assumptions participant 
a0Large11 = simulatePar(obs11Large, borders, alpha = 0)

# suspicious participant
aNeg1Large11 = simulatePar(obs11Large, borders, alpha = -1)
```

```{r}
par(mfrow = c(1,3))

# estimate alphas
a1Large11Fit = fitAlpha(a1Large11, gridLarge11)
plot(a1Large11Fit[,"alpha"], a1Large11Fit[,"prob"])
lines(a1Large11Fit[,"alpha"], a1Large11Fit[,"prob"])

a0Large11Fit = fitAlpha(a0Large11, gridLarge11)
plot(a0Large11Fit[,"alpha"], a0Large11Fit[,"prob"])
lines(a0Large11Fit[,"alpha"], a0Large11Fit[,"prob"])

aNeg1Large11Fit = fitAlpha(aNeg1Large11, gridLarge11)
plot(aNeg1Large11Fit[,"alpha"], aNeg1Large11Fit[,"prob"])
lines(x = aNeg1Large11Fit[,"alpha"], y = aNeg1Large11Fit[,"prob"])

```
```{r}
# Large rectangle 
largeRect = c(2,2,4,4)
# 1 positive 1 negative, Large
obs22Large = generateObs(2,2,largeRect)

# grid search
gridLarge22 = alphaGridSearch(borders, obs22Large)

# trusting participant
a1Large22 = simulatePar(obs22Large, borders, alpha = 1)

# weak sampling assumptions participant 
a0Large22 = simulatePar(obs22Large, borders, alpha = 0)

# suspicious participant
aNeg1Large22 = simulatePar(obs22Large, borders, alpha = -1)
```

```{r}
par(mfrow = c(1,3))

# estimate alphas
a1Large22Fit = fitAlpha(a1Large22, gridLarge22)
plot(a1Large22Fit[,"alpha"], a1Large22Fit[,"prob"])
lines(a1Large22Fit[,"alpha"], a1Large22Fit[,"prob"])

a0Large22Fit = fitAlpha(a0Large22, gridLarge22)
plot(a0Large22Fit[,"alpha"], a0Large22Fit[,"prob"])
lines(a0Large22Fit[,"alpha"], a0Large22Fit[,"prob"])

aNeg1Large22Fit = fitAlpha(aNeg1Large22, gridLarge22)
plot(aNeg1Large22Fit[,"alpha"], aNeg1Large22Fit[,"prob"])
lines(x = aNeg1Large22Fit[,"alpha"], y = aNeg1Large22Fit[,"prob"])

```

# Optimise over a larger area

Could a larger alpha distinguish between more rectangles?

```{r}
gridLargeLarger = alphaGridSearch(borders,obs11Large, alphaRange = seq(-5,5,1))
a5Large = simulatePar(obs11Large, borders, alpha = 5)
a5FitLarge =fitAlpha(a5Large, gridLargeLarger)
a5FitLarge
```

Doesn't seem like it. 

